In [1]:
import numpy

In [2]:
n = numpy.arange(27)
print(n)
type(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


numpy.ndarray

In [3]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [4]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
m = numpy.asarray([[1,2,3],[],[]], dtype=object)
print(m)

[list([1, 2, 3]) list([]) list([])]


In [6]:
import cv2

In [7]:
im = cv2.imread("016.1 smallgray.png.png",0)
im2 = cv2.imread("016.1 smallgray.png.png",1)

In [8]:
print(im)
print(im2)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [9]:
cv2.imwrite("016.2 newGray.png",im)

True

In [10]:
im[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [11]:
im[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [12]:
im.shape

(3, 5)

In [13]:
im[2,4]

182

In [14]:
for i in im: print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [15]:
for i in im.T: print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [16]:
for i in im.flat: print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [17]:
ims = numpy.hstack((im,im))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [18]:
ims = numpy.vstack((im,im))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
lst = numpy.hsplit(ims,2)
lst

ValueError: array split does not result in an equal division

In [20]:
lst = numpy.hsplit(ims,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [21]:
lst = numpy.vsplit(ims,2)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]